### PR TITLE
Banana Dashboard

### PR DESCRIPTION
**Pull request by manishdwibedy**
Pushing the banana dashboard files.

### CODE REVIEW

**Comment by karanjeets** [comment]
@manishdwibedy I have included Banana as a Git submodule. We need to make changes in this PR or raise a new one to get your dashboard added.

**Comment by chrismattmann** [comment]
guys where are we with this? @karanjeets @manishdwibedy

**Comment by karanjeets** [comment]
A basic version is available. Working with @manishdwibedy to get this committed.

image

**Comment by chrismattmann** [comment]
team let's get this committed 👍 thanks @karanjeets and @manishdwibedy

**Comment by arelaxend** [comment]
Hi, i am following the project and developing on my side for the moment based on sparkler.
What did you change from banana repo ? Did you only create "crawldb" file ?

**Comment by karanjeets** [comment]
@arelaxend Thanks for your comment here. First of all, I am going to close this PR without commit as we have already implemented better ways to include Banana project (Git Sub-Module and Maven Overlay). Please check [sparkler-ui](https://github.com/USCDataScience/sparkler/tree/master/sparkler-ui)

Yes, we created a dashboard file. I have modified it a little and will be pushing it as a separate commit. Secondly, we have added a sample file [module.js](https://github.com/USCDataScience/sparkler/blob/master/sparkler-ui/src/main/java/app/panels/sunburst/module.js) for SunBurst Banana plugin to show how to add custom modifications in the banana project. One good use case would be to have a "Stop Words" filter. 

Please let me know if I can help you with any more details.

**Comment by karanjeets** [comment]
@arelaxend Here is a basic banana dashboard for Sparkler (0).

(0): https://github.com/USCDataScience/sparkler/blob/master/sparkler-ui/dashboard/Sparkler-Dashboard-Basic

**Comment by thammegowda** [comment]
@karanjeets Please verify that the wiki/doc[0] is upto date and it reflects your recent changes 

[0] https://github.com/USCDataScience/sparkler/wiki/Sparkler-Dashboard---Setup

**Comment by arelaxend** [comment]
Everything works! Good job! 👍

**Pull request closed without merging**
