### PR TITLE
Sparkler-93: YAML backed config with Schema validation

### LINKED ISSUE #93: Revamp Sparkler Config - Type checking + Validation + *-site.yaml overriding
There are two FIXME: in configuration:

First, support loading `sparkler-defaults.yaml` and `sparkler-site.yaml`. The common practice is `*-default.yaml` provides default and recommended values from developers. The `*-site.yaml` should beused by users to customize or to override the defaults. Right now `sparkler-default.yaml` is supported and `sparkler-site.yaml` is not yet supported.

Second, towards the stability of system and fail early when errors are introduced by humans. 
Right now YAML configuration is transformed to JSON and internally it is treated as JSON. The system wouldn't know ahead of time if config is invalid. *There is no type check for values, no schema validation etc.* This could introduce errors to system and crash in later stages when the input config is invalid. As you see, except the config module, the rest of system is in staticly typed and strictly enforced. I think it will be nice to fail early when the config is invalid.

### PR DESCRIPTION
**Pull request by thammegowda**
## What changes were proposed in this pull request?

This PR replaces current JSON based config system with pure YAML based config system that supports type checking and schema validation.

Taking changes from #109, integrated it with Sparkler system, 
completely replaced  the older config with newer one.

Reorganized code, for instance `config` package is added and it is exposed to plugins

**Is this related to an already existing issue on sparkler?**  
Related to #93 and #109 

**Will it close an existing issue?**  
Closes #93 
Closes #109 

### How was this patch tested?

A few new tests are added by @SHASHANK-PRO-05 in #109 
The existing test are kept intact
All tests passed for `mvn clean test`

### CODE REVIEW

**Comment by thammegowda** [comment]
@SHASHANK-PRO-05 @karanjeets Give this a try and review the changes...

**Comment by SHASHANK-PRO-05** [comment]
@thammegowda I am getting a 
`java.lang.LinkageError: loader constraint violation: loader (instance of org/apache/felix/framework/BundleWiringImpl$BundleClassLoaderJava5) previously initiated loading for a different type with name "edu/usc/irds/sparkler/config/SparklerConfig"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.defineClass(BundleWiringImpl.java:2370)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.findClass(BundleWiringImpl.java:2154)
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1542)
	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:79)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2018)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)........`
probably SparklerConfig is loaded twice from classLoader

**Comment by thammegowda** [comment]
@SHASHANK-PRO-05  Not sure. Investigating

**Comment by chrismattmann** [comment]
closing since it's been years and this is way out of date

**Pull request closed without merging**
