### PR TITLE
WIP: ISSUE-215 Elasticsearch for Sparkler - Maven Profiles

### LINKED ISSUE #215: Elasticsearch for Sparkler - Maven Profiles
As part of the Elasticsearch for Sparkler set of issues, @lewismc requested the team create separate maven profiles for the solr and elasticsearch dependencies so we don't pull in unnecessary connectors when building the project.

### PR DESCRIPTION
**Pull request by KilometersFan**
## What changes were proposed in this pull request?

Changes to sparkler-app pom.xml:
- created two profiles, solr and elasticsearch, and added relevant dependencies

**Is this related to an already existing issue on sparkler?**  
 Related to #215 

**Will it close an existing issue?**  
Closes #215.

### How was this patch tested?
This was tested by building the project running `mvn clean compile package -P solr` and `mvn clean compile package -P elasticsearch` in the sparkler-app directory and running test crawls

### CODE REVIEW

**Review by lewismc — CHANGES_REQUESTED** [review]
Looking good. Each profile should only copy over the required resources it needs. A different way of saying this is that each profile should `exclude` any configuration that it doesn't need at runtime. You can take inspiration from https://stackoverflow.com/a/5663653

**Comment by lewismc** [comment]
@KilometersFan please update this PR. Thank you

**Comment by lewismc** [comment]
Let's hold off on merging this PR. We are still working on design of storage modules and need to make sure that work is solid before we progress further with the Maven build.

**Comment by buggtb** [comment]
Closing down as we no longer use maven.

**Pull request closed without merging**
