### PR TITLE
Mvn2sbt

### PR DESCRIPTION
**Pull request by buggtb**
Works, but needs some finishing off, but to expose it here, we have a working SBT build now.

Why move from Maven to SBT you ask? Because then IDE's can load up the code and work properly with the Java and Scala mix rather than the crazy state we were in with the old build.

### CODE REVIEW

**Comment by lewismc** [comment]
@buggtb nice work....
What finishing off does it need?
I will test this out when I get some time to focus on reviewing it properly.

**Comment by lewismc** [comment]
Looks like this could be merged @buggtb and then we could open subsequent issues to address shortcomings. WDYT?

**Comment by buggtb** [comment]
Okay got bored quickly, rest of this stuff is landing now. It looks like mush but we use it in production so whilst it may not have had wide spread testing, it is usable. i just need to document all the new stuff :)

**Comment by lewismc** [comment]
holy sparkler batman

**Comment by buggtb** [comment]
Just shoved an update that has a few fixes in, some updated internal libraries and a revamped default crawler that uses the more flexible Apache HTTP Client and has support both in Chrome and the default crawler for an HTTP Proxy (we tested/use ProxyMesh)

**Comment by lewismc** [comment]
@buggtb do you have a README for building now?

**Comment by buggtb** [comment]
Inside sparkler-core, just run `sbt package assembly` and it'll create the same build folder as old.

Once we get this merged down, we'll move our development directly against this repo on the usual branching strategy so that we don't have PR's like this again. I've also got proxy support, migration of plain crawls to apache httpclient and fixes for dodgy SSL sides and stuff that all need to go in once this is done.

**Comment by lewismc** [comment]
@buggtb I can't get a clean build because Javadoc generation fails... with quite a few issues. Do you also experience this behaviour?

**Comment by lewismc** [comment]
I mean I can jump in and start updating all of the Javadoc's if you want. That's not an issue. I just want to know if you have a clean build or not.

**Pull request merged**
