### PR TITLE
Fix for #78 and #79

### LINKED ISSUE #78: Add content limit in the default fetcher
No content limit encourages fetcher to retrieve all the content and keep it in memory. This results in OOM issues.

### PR DESCRIPTION
**Pull request by karanjeets**
Closes #78 and #79

### CODE REVIEW

**Comment by karanjeets** [comment]
@thammegowda Please review it buddy.

**Comment by thammegowda** [comment]
@karanjeets 
- we need to mark the resources as TRUNCATED
-  let tika parser skip them or not worry about them.

**Comment by thammegowda** [comment]
@karanjeets After you merge #90 I will be able to add a 'TRUNCATED=true' to the headers and merge this PR. Thanks.

**Comment by thammegowda** [comment]
UPDATE: Please add a test case.

If you need help/hints for writing a good test case:
1.  go to https://github.com/USCDataScience/sparkler/blob/master/sparkler-tests-base/src/main/java/edu/usc/irds/sparkler/test/TestSlaveServlet.java and create a `ZerosStreamingAction` [1]. example Query parameter `?action=zeros` (register it with the registry map in that class) 
2. Within the `ZerosStreamingAction extends TestAction` class, keep writing 0's to Response.writer. You may accept a queryparameter like  `size=<long>` to know how many zeros to stream. By default set it to `Integer.MAX`.
3. Write a test case in `FetcherDefaultTest` assert that you truncate at 64MB.


[1] https://en.wikipedia.org/wiki//dev/zero

**Comment by thammegowda** [comment]
Ping @karanjeets

Are you stuck? Is there something I can help you with?

**Comment by sujen1412** [comment]
@thammegowda @karanjeets , where is this PR stuck ? 
I faced the outlinkfilter throwing exceptions error recently and need to fix it. I did commit a change and saw this open PR and reverted it. Lets get this merged ?

**Comment by thammegowda** [comment]
@sujen1412 
The functionality was done, but it was waiting for a test case.

Looks like @karanjeets  abandoned this one.
I see there is a merge conflict now. I can't promise when I will be able to merge this, if you got some time, feel free to resolve the conflict and merge (Thanks).

**Comment by chrismattmann** [comment]
@thammegowda if you can fix the merge conflict, I will test and commit :) Deal?

**Comment by chrismattmann** [comment]
@thammegowda i cleared the merge conflict, but I think I messed something up.

**Comment by thammegowda** [comment]
@chrismattmann Fixed !

**Pull request merged**
